### ISSUE TITLE
Wrong error message - Assessment Submit

### ISSUE THREAD

**Issue by MichalGrzegorzak** [trustmark-2005-ltd/TrustMark-Retrofit-Integration#1]
Validation error returned:
 {"message":"Ventilation.ExistingVentilationProvided must be provided when ExistingVentilationProvided is 'Yes - Adequate'"}

I think it should be:
"VentilationType must be provided when ExistingVentilationProvided is 'Yes - Adequate'"

**Comment by PreppyGreen** [comment]
It should indeed, this has been corrected. Thanks for raising.
